package dev.notune.transcribe;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.security.GeneralSecurityException;
import java.util.Base64;
import javax.crypto.Cipher;
import javax.crypto.SecretKey;
import javax.crypto.spec.GCMParameterSpec;

/**
 * At-rest protection for the post-processing API key.
 *
 * <p><b>Threat model (accurate, not aspirational).</b> The credential lives in
 * the app-private {@code filesDir()} encrypted with AES-256-GCM under a key held
 * in Android Keystore. This protects the stored value against offline
 * extraction of app data that does not have the Keystore key — forensic copies
 * of the data partition, backup/transfer channels, other apps, or an attacker
 * reading files without root. It does <b>not</b> protect against a rooted or
 * otherwise compromised device while the app is using the key: the plaintext
 * must exist in process memory to build the {@code Authorization} header, and a
 * root attacker can read that memory or the Keystore-backed key itself. It also
 * does not protect against an attacker with physical access to a unlocked,
 * running device. Encryption at rest raises the cost of offline attacks; it is
 * not a guarantee.
 *
 * <p><b>Design constraints.</b>
 * <ul>
 *   <li>Never store plaintext or treat Base64 as protection (the legacy
 *       {@code pp_api_key} marker was Base64-encoded UTF-8 — encoding, not
 *       encryption).</li>
 *   <li>No hardcoded key: the AES key is generated by and never leaves
 *       AndroidKeyStore ({@link AndroidCredentialKeyProvider}); this class only
 *       ever receives a {@link SecretKey} through {@link KeyProvider}.</li>
 *   <li>Atomic persistence: writes go through {@link MarkerFileHelper}'s
 *       temp-file + fsync + rename path, so an interrupted update can never
 *       leave a partially written credential.</li>
 *   <li>Versioned, self-describing format: {@code v1:<b64 IV>:<b64 ciphertext>}.
 *       The prefix {@code v1:} is unambiguous against the legacy Base64 marker
 *       (Base64's alphabet has no {@code ':'}), so "new", "legacy" and
 *       "unsupported/corrupt" are always distinguishable.</li>
 *   <li>Explicit failures: missing, corrupt, tampered (GCM auth tag), truncated,
 *       unsupported-version and key-provider failures all raise
 *       {@link CredentialStoreException} — checked <em>and</em> unchecked
 *       provider failures alike (see the crypto boundary in {@link #store} /
 *       {@link #read}), so a malfunctioning
 *       Keystore produces an error the callers already handle instead of a
 *       crash. There is no code path that falls back to writing plaintext.
 *       Callers decide how to surface the error; this class never logs key
 *       material.</li>
 *   <li>The plaintext exists only as a transient in-memory {@code char[]}-like
 *       String used by the caller; nothing decrypted is ever written to disk or
 *       to a temporary file.</li>
 * </ul>
 *
 * <p><b>Legacy migration.</b> {@link #migrateLegacyMarkerIfNeeded()} detects the
 * old Base64 marker, encrypts it into the new store, <b>verifies</b> the
 * ciphertext round-trips, and only then removes the legacy copy. On any failure
 * the legacy marker is preserved untouched so the credential is never silently
 * lost or downgraded. Subsequent calls are idempotent: a secure file that still
 * decrypts short-circuits the migration. The prefs-era sources, the precedence
 * between the three historical homes, the sentinel and the retry policy live in
 * {@link CredentialMigration}, which drives this class.
 *
 * <p>Pure Java on purpose: {@code javax.crypto} AES-GCM works identically in
 * JVM unit tests (with a plain JCA key injected through {@link KeyProvider}) and
 * on device (with the AndroidKeyStore key), so every behaviour above except the
 * Keystore key acquisition itself is covered by {@code SecureCredentialStoreTest}.
 */
final class SecureCredentialStore {

    /** Encrypted credential marker in {@code filesDir()}. */
    static final String FILE_NAME = "pp_api_key_enc";

    /**
     * Legacy Base64 marker written by every release before this store existed.
     * Still read (never written) for compatibility until migration converts it.
     */
    static final String LEGACY_MARKER_FILE = "pp_api_key";

    /** Versioned prefix of the stored payload; see class doc. */
    static final String FORMAT_PREFIX = "v1:";

    private static final String TRANSFORMATION = "AES/GCM/NoPadding";
    private static final int GCM_TAG_BITS = 128;

    /**
     * Supplies the encryption key. The Android implementation resolves it from
     * AndroidKeyStore; tests inject a plain JCA key. Keystore-unavailable
     * surfaces here as {@link GeneralSecurityException} and is propagated —
     * never swallowed into a plaintext fallback.
     */
    interface KeyProvider {
        SecretKey get() throws GeneralSecurityException;
    }

    /** Explicit storage/crypto failure. Messages must never contain secrets. */
    static final class CredentialStoreException extends Exception {
        CredentialStoreException(String message) {
            super(message);
        }

        CredentialStoreException(String message, Throwable cause) {
            super(message, cause);
        }
    }

    /** Outcome of a legacy-marker migration attempt. */
    enum MigrationOutcome {
        /** Secure store already present and decryptable; nothing to migrate. */
        NOT_NEEDED,
        /** Legacy marker encrypted, verified, and removed. */
        MIGRATED,
        /** No legacy credential existed (fresh install / already migrated). */
        NO_LEGACY,
        /**
         * A marker file exists but is not decodable. It is preserved (never
         * deleted unread) and the migration will not be retried forever —
         * same policy the previous implementation applied to an undecodable
         * marker.
         */
        LEGACY_UNREADABLE,
        /**
         * The credential could not be encrypted right now (e.g. Keystore
         * unavailable). The legacy marker was preserved; a later start retries.
         */
        FAILED
    }

    private final File dir;
    private final KeyProvider keyProvider;

    SecureCredentialStore(File dir, KeyProvider keyProvider) {
        if (dir == null || keyProvider == null) {
            throw new IllegalArgumentException("dir and keyProvider are required");
        }
        this.dir = dir;
        this.keyProvider = keyProvider;
    }

    // ------------------------------------------------------------------
    // Format layer (pure; exercised directly by tests)
    // ------------------------------------------------------------------

    /**
     * Encrypts {@code plaintext} into the {@code v1:} storage format with a
     * fresh, randomly generated 96-bit IV per call (GCM's standard nonce size).
     * When the key provider is an AndroidKeyStore key the IV is generated by
     * the Keystore itself (randomized encryption), which is why no IV is passed
     * in on encrypt — the caller reads it back from the {@link Cipher}.
     */
    static String encryptToString(SecretKey key, String plaintext)
            throws GeneralSecurityException {
        Cipher cipher = Cipher.getInstance(TRANSFORMATION);
        cipher.init(Cipher.ENCRYPT_MODE, key);
        byte[] iv = cipher.getIV();
        byte[] ciphertext = cipher.doFinal(plaintext.getBytes(StandardCharsets.UTF_8));
        Base64.Encoder b64 = Base64.getEncoder();
        return FORMAT_PREFIX + b64.encodeToString(iv) + ":" + b64.encodeToString(ciphertext);
    }

    /**
     * Decrypts a {@code v1:} payload. Any structural problem (wrong prefix,
     * unsupported version, missing/truncated fields) or cryptographic problem
     * (tampered ciphertext or IV — GCM's authentication tag rejects both) is
     * reported as {@link CredentialStoreException}; the caller must not treat
     * any of them as "no credential" plus a plaintext fallback.
     */
    static String decryptFromString(SecretKey key, String stored)
            throws CredentialStoreException, GeneralSecurityException {
        if (stored == null || stored.isEmpty()) {
            throw new CredentialStoreException("credential store is empty");
        }
        if (!stored.startsWith(FORMAT_PREFIX)) {
            // Distinguishes an unsupported future version ("v2:...") from
            // random corruption without echoing the stored bytes.
            throw new CredentialStoreException(
                    "unsupported or corrupt credential format version");
        }
        String body = stored.substring(FORMAT_PREFIX.length());
        int separator = body.indexOf(':');
        if (separator <= 0 || separator == body.length() - 1) {
            throw new CredentialStoreException("truncated credential payload");
        }
        byte[] iv;
        byte[] ciphertext;
        try {
            Base64.Decoder b64 = Base64.getDecoder();
            iv = b64.decode(body.substring(0, separator));
            ciphertext = b64.decode(body.substring(separator + 1));
        } catch (IllegalArgumentException e) {
            throw new CredentialStoreException("credential payload is not valid base64", e);
        }
        if (iv.length == 0 || ciphertext.length == 0) {
            throw new CredentialStoreException("credential payload has empty fields");
        }
        Cipher cipher = Cipher.getInstance(TRANSFORMATION);
        cipher.init(Cipher.DECRYPT_MODE, key, new GCMParameterSpec(GCM_TAG_BITS, iv));
        try {
            byte[] plain = cipher.doFinal(ciphertext);
            return new String(plain, StandardCharsets.UTF_8);
        } catch (GeneralSecurityException e) {
            // AEADBadTagException (tampered/wrong key) or similar. The message
            // carries no key material, but keep the diagnostic generic anyway.
            throw new CredentialStoreException("credential failed authentication", e);
        }
    }

    /** Whether {@code raw} is in the legacy Base64 (pre-encryption) format. */
    static boolean isLegacyFormat(String raw) {
        if (raw == null || raw.isEmpty() || raw.startsWith(FORMAT_PREFIX)) return false;
        try {
            return Base64.getDecoder().decode(raw).length > 0;
        } catch (IllegalArgumentException e) {
            return false;
        }
    }

    /** Decodes a legacy Base64 marker value to the original plaintext key. */
    static String decodeLegacy(String raw) throws CredentialStoreException {
        if (!isLegacyFormat(raw)) {
            throw new CredentialStoreException("legacy credential is not valid base64");
        }
        return new String(Base64.getDecoder().decode(raw), StandardCharsets.UTF_8);
    }

    // ------------------------------------------------------------------
    // Operations
    // ------------------------------------------------------------------

    /** True when the secure store file exists (cheap; touches no Keystore). */
    boolean exists() {
        return new File(dir, FILE_NAME).isFile();
    }

    /**
     * Sanitized diagnostic suffix: the exception's class name, never its message.
     *
     * <p>Key acquisition and the cipher fail in two shapes on Android. The
     * expected, documented ones are checked — {@code KeyStoreException} from an
     * unopenable Keystore, {@code UnrecoverableKeyException} from an invalidated
     * key — and were always handled. A Keystore or JCA provider that is merely in
     * a bad state throws unchecked ones instead ({@code IllegalStateException},
     * {@code ProviderException}), which used to escape the
     * {@code catch (GeneralSecurityException)} in {@link #store} and {@link #read}
     * and reach the settings screen or the start-up migration as a crash. Both
     * shapes are now caught at those crypto boundaries — deliberately not with a
     * blanket {@code catch (Throwable)}, which would also hide unrelated defects —
     * and become the one typed failure callers handle, naming the real failure
     * mode rather than a wrapper around it.
     *
     * <p>Provider messages are never embedded in that diagnostic: they can echo
     * key material, aliases or file paths.
     */
    private static String reason(Throwable failure) {
        return failure.getClass().getSimpleName();
    }

    /**
     * Encrypts {@code secret}, persists it atomically, then reads it back and
     * decrypts it to prove the write landed intact before reporting success.
     *
     * @throws CredentialStoreException if key acquisition, encryption, the write,
     *         or the verification round-trip failed; nothing plaintext is ever
     *         written, and a write that did not land leaves the previous payload
     *         (so a failed update keeps the credential that was already stored)
     */
    void store(String secret) throws CredentialStoreException {
        if (secret == null || secret.isEmpty()) {
            throw new CredentialStoreException("refusing to store an empty credential");
        }

        // Key + cipher boundary: the only place a provider failure can originate
        // before anything is written.
        String payload;
        try {
            payload = encryptToString(keyProvider.get(), secret);
        } catch (GeneralSecurityException | RuntimeException e) {
            // Key acquisition + cipher: a checked Keystore failure, an invalidated
            // key and an unchecked provider-state failure all end up here and
            // become the typed error the callers already handle.
            throw new CredentialStoreException(
                    "credential encryption failed (" + reason(e) + ")", e);
        }

        MarkerFileHelper.writeStringToFile(dir, FILE_NAME, payload);
        String written = MarkerFileHelper.readStringFromFile(dir, FILE_NAME, null);
        String verified = null;
        if (written != null) {
            try {
                verified = decryptFromString(keyProvider.get(), written);
            } catch (GeneralSecurityException | RuntimeException e) {
                // A structural failure throws CredentialStoreException from
                // decryptFromString and keeps its specific message; this covers the
                // provider-side failures of the verification decrypt.
                throw new CredentialStoreException(
                        "encrypted credential could not be verified after writing ("
                                + reason(e) + ")", e);
            }
        }
        if (!secret.equals(verified)) {
            throw new CredentialStoreException(
                    "encrypted credential could not be verified after writing");
        }
    }

    /**
     * Returns the decrypted credential, or {@code null} when no credential is
     * stored.
     *
     * @throws CredentialStoreException when the stored value exists but cannot
     *         be trusted (corrupt, tampered, truncated, unsupported version) or
     *         cannot be decrypted right now (key invalidated, Keystore unavailable
     *         or in a bad state). Callers surface this as an explicit error —
     *         never as an empty success, and never as a fallback to a legacy copy
     *         while an encrypted payload exists.
     */
    String read() throws CredentialStoreException {
        String stored = MarkerFileHelper.readStringFromFile(dir, FILE_NAME, null);
        if (stored == null || stored.isEmpty()) {
            return null;
        }
        try {
            return decryptFromString(keyProvider.get(), stored);
        } catch (GeneralSecurityException | RuntimeException e) {
            // Covers an invalidated/unavailable key and a provider-state failure,
            // not only a wrong or tampered payload. decryptFromString's own
            // CredentialStoreException (format, authentication) is not caught here
            // and keeps its specific diagnostic.
            throw new CredentialStoreException(
                    "credential could not be decrypted (" + reason(e) + ")", e);
        }
    }

    /** Removes the secure store file. Idempotent. */
    boolean delete() {
        File file = new File(dir, FILE_NAME);
        if (!file.exists()) return true;
        // Deleting an encrypted file on flash storage does not securely
        // erase the blocks (wear-levelling/FTL keep copies); this removes
        // the app's access to the credential, it does not guarantee the
        // bytes are unrecoverable from the medium.
        //
        // The result is returned, never swallowed: a failed unlink leaves the
        // credential here, still readable, and a caller that reported "deleted"
        // would be stating something false about the user's secret. Callers on
        // the deletion path must check it.
        return file.delete();
    }

    // ------------------------------------------------------------------
    // Legacy marker migration (the Format-A path; prefs-based legacy sources
    // are handled by SettingsManager, which needs a Context for SharedPreferences)
    // ------------------------------------------------------------------

    /** Reads the legacy Base64 marker if present and non-empty, else null. */
    String readLegacyMarker() {
        String raw = MarkerFileHelper.readStringFromFile(dir, LEGACY_MARKER_FILE, null);
        if (raw == null || raw.isEmpty()) return null;
        return raw;
    }

    /**
     * Removes the legacy marker file. Callers invoke this ONLY after
     * {@link #store} has verified the encrypted replacement.
     */
    void deleteLegacyMarker() {
        File file = new File(dir, LEGACY_MARKER_FILE);
        if (file.exists()) file.delete();
    }

    /**
     * Converts the legacy Base64 marker (if any) into the encrypted store.
     *
     * <p>Order guarantees: the encrypted write is verified round-trip before
     * the legacy marker is deleted; on any failure the legacy marker is left
     * untouched and {@link MigrationOutcome#FAILED} is returned, so an
     * interrupted or impossible migration (Keystore unavailable) never loses
     * the user's credential and never rewrites it as plaintext.
     */
    MigrationOutcome migrateLegacyMarkerIfNeeded() {
        if (exists()) {
            // The secure store is authoritative. A leftover legacy marker can
            // only be a stale copy from a downgrade cycle; remove it only after
            // confirming the secure copy still decrypts.
            try {
                if (read() != null) {
                    deleteLegacyMarker();
                    return MigrationOutcome.NOT_NEEDED;
                }
            } catch (CredentialStoreException e) {
                // Corrupt secure store: fall through so an existing legacy
                // marker (preserved by a previously failed migration) can
                // rebuild it rather than the credential becoming unreachable.
            }
        }
        String raw = readLegacyMarker();
        if (raw == null) {
            return MigrationOutcome.NO_LEGACY;
        }
        String plaintext;
        try {
            plaintext = decodeLegacy(raw);
        } catch (CredentialStoreException e) {
            // Present but unreadable: report, do not delete what we cannot
            // read, and do not claim success.
            return MigrationOutcome.LEGACY_UNREADABLE;
        }
        if (plaintext.isEmpty()) {
            deleteLegacyMarker();
            return MigrationOutcome.NO_LEGACY;
        }
        try {
            store(plaintext);
        } catch (CredentialStoreException e) {
            // Legacy marker deliberately untouched: it is still the only copy.
            return MigrationOutcome.FAILED;
        }
        // Verified round-trip inside store(): safe to drop the legacy copy now.
        deleteLegacyMarker();
        return MigrationOutcome.MIGRATED;
    }
}
